In [4]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5]) 
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) 

arr_sum = arr1 + 10 
arr_product = arr2 * 2

element_at_index_2 = arr1[2] 
sliced_arr1 = arr1[1:4] 
sliced_arr2 = arr2[:, 1]

shape_of_arr2 = arr2.shape 
dimensions_of_arr2 = arr2.ndim

# Reshape the array
reshaped_arr1 = arr1.reshape((5, 1))
print("Original 1D array:")
print(arr1)
print("\nOriginal 2D array:")
print(arr2)

print("\nArray operations:")
print("arr1 + 10:", arr_sum)
print("arr2 * 2:", arr_product)

print("\nArray slicing:")
print("Element at index 2:", element_at_index_2)
print("Sliced arr1:", sliced_arr1)
print("Second column of arr2:", sliced_arr2)
print("\nArray shape and dimensions:")
print("Shape of arr2:", shape_of_arr2)
print("Number of dimensions in arr2:", dimensions_of_arr2)
print("\nReshaped array:")
print(reshaped_arr1)

Original 1D array:
[1 2 3 4 5]

Original 2D array:
[[1 2 3]
 [4 5 6]]

Array operations:
arr1 + 10: [11 12 13 14 15]
arr2 * 2: [[ 2  4  6]
 [ 8 10 12]]

Array slicing:
Element at index 2: 3
Sliced arr1: [2 3 4]
Second column of arr2: [2 5]

Array shape and dimensions:
Shape of arr2: (2, 3)
Number of dimensions in arr2: 2

Reshaped array:
[[1]
 [2]
 [3]
 [4]
 [5]]
